[phases.setup]
nixPkgs = ["ffmpeg", "libsndfile"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"









