services:
  # FastAPI Backend
  - type: web
    name: subitai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BACKEND_CORS_ORIGINS
        sync: false
      - key: LOG_LEVEL
        value: info

  # Celery Worker (for background transcription tasks)
  - type: worker
    name: subitai-celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A workers.celery worker --loglevel=info
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: LOG_LEVEL
        value: info
