/**
 * SubitAI Subtitle Style Library
 * Full catalog inspired by diveo.io with 56 presets
 * BASIC: 10 styles, DYNAMIC: 34 styles, WORD: 12 styles
 */

export interface SubtitlePreset {
    id: string;
    name: string;
    category: 'BASIC' | 'DYNAMIC' | 'WORD';
    style: {
        fontFamily: string;
        fontSize: number;
        fontWeight: 'normal' | 'bold' | '600' | '700';
        color: string;
        backgroundColor: string;
        backgroundOpacity: number;
        textAlign: 'left' | 'center' | 'right';
        position: 'bottom' | 'center' | 'top';
        verticalOffset: number;
        outlineColor: string;
        outlineWidth: number;
        borderRadius: number;
        padding: number;
        letterSpacing: number;
        lineHeight: number;
        textShadow?: string;
        animationIn?: string;
        displayMode?: 'line-by-line' | 'word-highlight' | 'word-only';
        highlightColor?: string;
        highlightScale?: number;
        highlightBackground?: string;
        textTransform?: 'none' | 'uppercase' | 'lowercase';
        fontStyle?: 'normal' | 'italic';
    };
}

// ============================================================================
// BASIC CATEGORY - 10 Standard subtitle styles
// ============================================================================

const BASIC_PRESETS: SubtitlePreset[] = [
    {
        id: 'basic-classic-dark',
        name: 'Classic Dark',
        category: 'BASIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 24,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#000000',
            backgroundOpacity: 0.7,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: '#000000',
            outlineWidth: 0,
            borderRadius: 8,
            padding: 12,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-modern-bold',
        name: 'Modern Bold',
        category: 'BASIC',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-blue-banner',
        name: 'Blue Banner',
        category: 'BASIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#3B82F6',
            backgroundOpacity: 1,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: 'transparent',
            outlineWidth: 0,
            borderRadius: 12,
            padding: 14,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-yellow-italic',
        name: 'Yellow Italic',
        category: 'BASIC',
        style: {
            fontFamily: 'Quicksand',
            fontSize: 26,
            fontWeight: '600',
            color: '#FACC15',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0.5,
            lineHeight: 1.3,
            displayMode: 'line-by-line',
            fontStyle: 'italic',
        },
    },
    {
        id: 'basic-yellow-outline',
        name: 'Yellow Outline',
        category: 'BASIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#FACC15',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.2,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-red-shadow',
        name: 'Red Shadow',
        category: 'BASIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.1,
            textShadow: '4px 4px 0px #EF4444',
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-minimalist',
        name: 'Minimalist',
        category: 'BASIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: '600',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 12,
            outlineColor: '#000000',
            outlineWidth: 1,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.5,
            textShadow: '1px 1px 3px rgba(0,0,0,0.8)',
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-pink-banner',
        name: 'Pink Banner',
        category: 'BASIC',
        style: {
            fontFamily: 'Poppins',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#EC4899',
            backgroundOpacity: 1,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: 'transparent',
            outlineWidth: 0,
            borderRadius: 10,
            padding: 14,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-green-banner',
        name: 'Green Banner',
        category: 'BASIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#22C55E',
            backgroundOpacity: 1,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: 'transparent',
            outlineWidth: 0,
            borderRadius: 10,
            padding: 14,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'basic-white-outline',
        name: 'White Outline',
        category: 'BASIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#FFFFFF',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'line-by-line',
        },
    },
];

// ============================================================================
// DYNAMIC CATEGORY - 34 Word highlighting styles
// ============================================================================

const DYNAMIC_PRESETS: SubtitlePreset[] = [
    // Row 1 from screenshots
    {
        id: 'dynamic-pink-highlight',
        name: 'Pink Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#EC4899',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-all-caps-white',
        name: 'All Caps White',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FACC15',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
            textTransform: 'uppercase',
        },
    },
    {
        id: 'dynamic-brown-highlight',
        name: 'Brown Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 24,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#A16207',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-red-highlight',
        name: 'Red Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 24,
            fontWeight: '600',
            color: '#FFFFFF',
            highlightColor: '#EF4444',
            highlightBackground: '#EF4444',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-italic-blue',
        name: 'Italic Blue',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Quicksand',
            fontSize: 24,
            fontWeight: '600',
            color: '#FFFFFF',
            highlightColor: '#3B82F6',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
            fontStyle: 'italic',
        },
    },
    {
        id: 'dynamic-multi-line-caps',
        name: 'Multi-Line Caps',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#22C55E',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.1,
            displayMode: 'word-highlight',
            textTransform: 'uppercase',
        },
    },
    {
        id: 'dynamic-white-box',
        name: 'White Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#000000',
            highlightColor: '#000000',
            highlightBackground: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: 'transparent',
            outlineWidth: 0,
            borderRadius: 4,
            padding: 8,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-pink-box',
        name: 'Pink Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: '600',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#EC4899',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 4,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    // Row 2
    {
        id: 'dynamic-green-highlight',
        name: 'Green Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#22C55E',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-yellow-karaoke',
        name: 'Yellow Karaoke',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 26,
            fontWeight: '700',
            color: '#A0A0A0',
            highlightColor: '#FACC15',
            backgroundColor: 'rgba(0,0,0,0.6)',
            backgroundOpacity: 0.6,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 12,
            padding: 16,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-purple-box',
        name: 'Purple Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#8B5CF6',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 8,
            padding: 8,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-purple-pop',
        name: 'Purple Pop',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#D1D5DB',
            highlightColor: '#A855F7',
            highlightScale: 1.15,
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-orange-wave',
        name: 'Orange Wave',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Poppins',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#F97316',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-teal-glow',
        name: 'Teal Glow',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#E5E7EB',
            highlightColor: '#14B8A6',
            backgroundColor: 'rgba(0,0,0,0.5)',
            backgroundOpacity: 0.5,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 10,
            padding: 14,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
            textShadow: '0 0 10px #14B8A6',
        },
    },
    {
        id: 'dynamic-red-fire',
        name: 'Red Fire',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 30,
            fontWeight: 'bold',
            color: '#FBBF24',
            highlightColor: '#EF4444',
            highlightScale: 1.1,
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    // Row 3 from dynamic screenshots
    {
        id: 'dynamic-cyan-highlight',
        name: 'Cyan Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 24,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#06B6D4',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-plain-white',
        name: 'Plain White',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 24,
            fontWeight: '600',
            color: '#9CA3AF',
            highlightColor: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-green-box',
        name: 'Green Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#22C55E',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 4,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-italic-pink',
        name: 'Italic Pink',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Quicksand',
            fontSize: 26,
            fontWeight: '600',
            color: '#FFFFFF',
            highlightColor: '#EC4899',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
            fontStyle: 'italic',
        },
    },
    {
        id: 'dynamic-lowercase-white',
        name: 'Lowercase White',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 24,
            fontWeight: '600',
            color: '#9CA3AF',
            highlightColor: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
            textTransform: 'lowercase',
        },
    },
    {
        id: 'dynamic-caps-green',
        name: 'Caps Green',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#22C55E',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
            textTransform: 'uppercase',
        },
    },
    {
        id: 'dynamic-blue-box',
        name: 'Blue Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#3B82F6',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 4,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-yellow-caps',
        name: 'Yellow Caps',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FACC15',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
            textTransform: 'uppercase',
        },
    },
    // Additional dynamic styles
    {
        id: 'dynamic-neon-green',
        name: 'Neon Green',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#D1FAE5',
            highlightColor: '#10B981',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
            textShadow: '0 0 8px #10B981',
        },
    },
    {
        id: 'dynamic-amber-highlight',
        name: 'Amber Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Poppins',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#F59E0B',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-rose-highlight',
        name: 'Rose Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#F43F5E',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-indigo-box',
        name: 'Indigo Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 24,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#6366F1',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 6,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-lime-highlight',
        name: 'Lime Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#84CC16',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-sky-highlight',
        name: 'Sky Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Poppins',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#0EA5E9',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-violet-pop',
        name: 'Violet Pop',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#D1D5DB',
            highlightColor: '#7C3AED',
            highlightScale: 1.12,
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-fuchsia-highlight',
        name: 'Fuchsia Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#D946EF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-orange-box',
        name: 'Orange Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#F97316',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 4,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'dynamic-emerald-glow',
        name: 'Emerald Glow',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#D1FAE5',
            highlightColor: '#059669',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
            textShadow: '0 0 10px #059669',
        },
    },
    {
        id: 'dynamic-red-box',
        name: 'Red Box',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#DC2626',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 4,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
];

// ============================================================================
// WORD CATEGORY - 12 Single word display styles
// ============================================================================

const WORD_PRESETS: SubtitlePreset[] = [
    {
        id: 'word-white-bold',
        name: 'White Bold',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 48,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 5,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-white-light',
        name: 'White Light',
        category: 'WORD',
        style: {
            fontFamily: 'Inter',
            fontSize: 44,
            fontWeight: '600',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-green',
        name: 'Green Word',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 48,
            fontWeight: 'bold',
            color: '#22C55E',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-pink-italic',
        name: 'Pink Italic',
        category: 'WORD',
        style: {
            fontFamily: 'Quicksand',
            fontSize: 46,
            fontWeight: '600',
            color: '#EC4899',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1,
            displayMode: 'word-only',
            fontStyle: 'italic',
        },
    },
    {
        id: 'word-red-strike',
        name: 'Red Strike',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 48,
            fontWeight: 'bold',
            color: '#EF4444',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-yellow-highlight',
        name: 'Yellow Highlight',
        category: 'WORD',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 44,
            fontWeight: 'bold',
            color: '#000000',
            highlightBackground: '#FACC15',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: 'transparent',
            outlineWidth: 0,
            borderRadius: 4,
            padding: 12,
            letterSpacing: 1,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-red-outline',
        name: 'Red Outline',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 50,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#EF4444',
            outlineWidth: 5,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-simple-white',
        name: 'Simple White',
        category: 'WORD',
        style: {
            fontFamily: 'Inter',
            fontSize: 40,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-strikethrough',
        name: 'Strikethrough',
        category: 'WORD',
        style: {
            fontFamily: 'Inter',
            fontSize: 42,
            fontWeight: '600',
            color: '#9CA3AF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'word-bold-caps',
        name: 'Bold Caps',
        category: 'WORD',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 52,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 5,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 3,
            lineHeight: 1,
            displayMode: 'word-only',
            textTransform: 'uppercase',
        },
    },
    {
        id: 'word-italic-white',
        name: 'Italic White',
        category: 'WORD',
        style: {
            fontFamily: 'Quicksand',
            fontSize: 46,
            fontWeight: '600',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1,
            displayMode: 'word-only',
            fontStyle: 'italic',
        },
    },
    {
        id: 'word-yellow-gold',
        name: 'Yellow Gold',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 48,
            fontWeight: 'bold',
            color: '#FACC15',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
];

// ============================================================================
// EXPORT ALL PRESETS
// ============================================================================

export const STYLE_PRESETS: SubtitlePreset[] = [
    ...BASIC_PRESETS,
    ...DYNAMIC_PRESETS,
    ...WORD_PRESETS,
];

// Helper to get presets by category
export const getPresetsByCategory = (category: 'BASIC' | 'DYNAMIC' | 'WORD'): SubtitlePreset[] => {
    return STYLE_PRESETS.filter(p => p.category === category);
};

// Safe zone padding for subtitle positioning
export const SAFE_ZONE_PADDING = 0.1; // 10% from edges
