/**
 * SubitAI Subtitle Style Library
 * This file contains the default presets for the subtitle engine.
 * Inspired by popular caption styles from social media platforms.
 */

export interface SubtitlePreset {
    id: string;
    name: string;
    category: 'BASIC' | 'DYNAMIC' | 'WORD';
    style: {
        fontFamily: string;
        fontSize: number; // Base size, will be scaled
        fontWeight: 'normal' | 'bold' | '600' | '700';
        color: string;
        backgroundColor: string;
        backgroundOpacity: number;
        textAlign: 'left' | 'center' | 'right';
        position: 'bottom' | 'center' | 'top';
        verticalOffset: number; // % from edge
        outlineColor: string;
        outlineWidth: number;
        borderRadius: number;
        padding: number;
        letterSpacing: number;
        lineHeight: number;
        textShadow?: string;
        animationIn?: string;
        // For DYNAMIC/WORD styles
        displayMode?: 'line-by-line' | 'word-highlight' | 'word-only';
        highlightColor?: string;
        highlightScale?: number;
        highlightBackground?: string;
    };
}

// ============================================================================
// BASIC CATEGORY - Standard, reliable subtitle styles
// ============================================================================

const BASIC_PRESETS: SubtitlePreset[] = [
    {
        id: 'classic-dark',
        name: 'Classic Dark',
        category: 'BASIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 24,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#000000',
            backgroundOpacity: 0.7,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: '#000000',
            outlineWidth: 0,
            borderRadius: 8,
            padding: 12,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'modern-bold',
        name: 'Modern Bold',
        category: 'BASIC',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'blue-banner',
        name: 'Blue Banner',
        category: 'BASIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#3B82F6',
            backgroundOpacity: 1,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: 'transparent',
            outlineWidth: 0,
            borderRadius: 12,
            padding: 14,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'yellow-italic',
        name: 'Yellow Italic',
        category: 'BASIC',
        style: {
            fontFamily: 'Quicksand',
            fontSize: 26,
            fontWeight: '600',
            color: '#FACC15',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0.5,
            lineHeight: 1.3,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'yellow-outline',
        name: 'Yellow Outline',
        category: 'BASIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#FACC15',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.2,
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'red-shadow',
        name: 'Red Shadow',
        category: 'BASIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.1,
            textShadow: '4px 4px 0px #EF4444',
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'minimalist-white',
        name: 'Minimalist',
        category: 'BASIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 22,
            fontWeight: '600',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 12,
            outlineColor: '#000000',
            outlineWidth: 1,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.5,
            textShadow: '1px 1px 3px rgba(0,0,0,0.8)',
            displayMode: 'line-by-line',
        },
    },
    {
        id: 'pink-banner',
        name: 'Pink Banner',
        category: 'BASIC',
        style: {
            fontFamily: 'Poppins',
            fontSize: 22,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#EC4899',
            backgroundOpacity: 1,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: 'transparent',
            outlineWidth: 0,
            borderRadius: 10,
            padding: 14,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'line-by-line',
        },
    },
];

// ============================================================================
// DYNAMIC CATEGORY - Word highlighting styles
// ============================================================================

const DYNAMIC_PRESETS: SubtitlePreset[] = [
    {
        id: 'green-highlight',
        name: 'Green Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 30,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#22C55E',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'pink-highlight',
        name: 'Pink Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 30,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#EC4899',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'yellow-karaoke',
        name: 'Yellow Karaoke',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 26,
            fontWeight: '700',
            color: '#A0A0A0',
            highlightColor: '#FACC15',
            backgroundColor: 'rgba(0,0,0,0.6)',
            backgroundOpacity: 0.6,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 12,
            padding: 16,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
            animationIn: 'fade',
        },
    },
    {
        id: 'box-highlight',
        name: 'Box Highlight',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#FFFFFF',
            highlightBackground: '#8B5CF6',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 8,
            padding: 8,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'purple-pop',
        name: 'Purple Pop',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#D1D5DB',
            highlightColor: '#A855F7',
            highlightScale: 1.15,
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'orange-wave',
        name: 'Orange Wave',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Poppins',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#F97316',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 18,
            outlineColor: '#000000',
            outlineWidth: 3,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1.3,
            displayMode: 'word-highlight',
        },
    },
    {
        id: 'teal-glow',
        name: 'Teal Glow',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Inter',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#E5E7EB',
            highlightColor: '#14B8A6',
            backgroundColor: 'rgba(0,0,0,0.5)',
            backgroundOpacity: 0.5,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 15,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 10,
            padding: 14,
            letterSpacing: 0,
            lineHeight: 1.4,
            displayMode: 'word-highlight',
            textShadow: '0 0 10px #14B8A6',
        },
    },
    {
        id: 'red-fire',
        name: 'Red Fire',
        category: 'DYNAMIC',
        style: {
            fontFamily: 'Anton',
            fontSize: 30,
            fontWeight: 'bold',
            color: '#FBBF24',
            highlightColor: '#EF4444',
            highlightScale: 1.1,
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'bottom',
            verticalOffset: 20,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1.2,
            displayMode: 'word-highlight',
        },
    },
];

// ============================================================================
// WORD CATEGORY - Single word display styles
// ============================================================================

const WORD_PRESETS: SubtitlePreset[] = [
    {
        id: 'hormozi-pop',
        name: 'Hormozi Pop',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 48,
            fontWeight: 'bold',
            color: '#FFFFFF',
            highlightColor: '#22C55E',
            highlightScale: 1.2,
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 6,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
            animationIn: 'pop',
        },
    },
    {
        id: 'single-bold',
        name: 'Single Bold',
        category: 'WORD',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 52,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 5,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'teal-word',
        name: 'Teal Accent',
        category: 'WORD',
        style: {
            fontFamily: 'Montserrat',
            fontSize: 46,
            fontWeight: 'bold',
            color: '#14B8A6',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'yellow-flash',
        name: 'Yellow Flash',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 50,
            fontWeight: 'bold',
            color: '#FACC15',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 5,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
            animationIn: 'pop',
        },
    },
    {
        id: 'minimal-word',
        name: 'Minimalist Word',
        category: 'WORD',
        style: {
            fontFamily: 'Inter',
            fontSize: 40,
            fontWeight: '700',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 2,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 0,
            lineHeight: 1,
            displayMode: 'word-only',
            textShadow: '2px 2px 8px rgba(0,0,0,0.8)',
        },
    },
    {
        id: 'impact-word',
        name: 'Impact Word',
        category: 'WORD',
        style: {
            fontFamily: 'Anton',
            fontSize: 56,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 6,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 3,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'outlined-word',
        name: 'Outlined Word',
        category: 'WORD',
        style: {
            fontFamily: 'Archivo Black',
            fontSize: 48,
            fontWeight: 'bold',
            color: 'transparent',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#FFFFFF',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 2,
            lineHeight: 1,
            displayMode: 'word-only',
        },
    },
    {
        id: 'pink-word',
        name: 'Pink Word',
        category: 'WORD',
        style: {
            fontFamily: 'Poppins',
            fontSize: 46,
            fontWeight: 'bold',
            color: '#EC4899',
            backgroundColor: 'transparent',
            backgroundOpacity: 0,
            textAlign: 'center',
            position: 'center',
            verticalOffset: 50,
            outlineColor: '#000000',
            outlineWidth: 4,
            borderRadius: 0,
            padding: 0,
            letterSpacing: 1,
            lineHeight: 1,
            displayMode: 'word-only',
            animationIn: 'fade',
        },
    },
];

// ============================================================================
// EXPORT ALL PRESETS
// ============================================================================

export const STYLE_PRESETS: SubtitlePreset[] = [
    ...BASIC_PRESETS,
    ...DYNAMIC_PRESETS,
    ...WORD_PRESETS,
];

// Helper to get presets by category
export const getPresetsByCategory = (category: 'BASIC' | 'DYNAMIC' | 'WORD'): SubtitlePreset[] => {
    return STYLE_PRESETS.filter(p => p.category === category);
};

// Safe zone padding for subtitle positioning
export const SAFE_ZONE_PADDING = 0.1; // 10% from edges
